name: Test Environment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '22'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Gradle Wrapper   
        working-directory: gradlerepo
        run: gradle wrapper

      - name: Grant execute permission
        working-directory: gradlerepo
        run: chmod +x gradlew

      - name: Run Integration Tests
        working-directory: gradlerepo
        run: ./gradlew test
      
      - name: Restore Allure History
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: gradlerepo/build/allure-results/history
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: gradlerepo/build/allure-results
          allure_report: gradlerepo/build/allure-report
          keep_reports: 20
      
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: gradlerepo/build/allure-report

      - name: Save Allure History
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: gradlerepo/build/allure-report/history